# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/space_invaders_bd/space_invaders_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_invaders_bd || ORIG_REF_NAME==space_invaders_bd} -quiet] -quiet

# IP: bd/space_invaders_bd/ip/space_invaders_bd_processing_system7_0_0/space_invaders_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_invaders_bd_processing_system7_0_0 || ORIG_REF_NAME==space_invaders_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/space_invaders_bd/ip/space_invaders_bd_space_invaders_ip_0_0/space_invaders_bd_space_invaders_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_invaders_bd_space_invaders_ip_0_0 || ORIG_REF_NAME==space_invaders_bd_space_invaders_ip_0_0} -quiet] -quiet

# IP: bd/space_invaders_bd/ip/space_invaders_bd_ps7_0_axi_periph_0/space_invaders_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_invaders_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==space_invaders_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/space_invaders_bd/ip/space_invaders_bd_rst_ps7_0_50M_0/space_invaders_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_invaders_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==space_invaders_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/space_invaders_bd/ip/space_invaders_bd_auto_pc_0/space_invaders_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==space_invaders_bd_auto_pc_0 || ORIG_REF_NAME==space_invaders_bd_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/aboua/OneDrive/Desktop/projects/space_invaders_soc/space_invaders_soc.gen/sources_1/bd/space_invaders_bd/space_invaders_bd_ooc.xdc
